[package]
name = "pistolet"
version = "0.1.0"
authors = ["MisakaCenter <misaka@sjtu.edu.cn>"]
edition = "2018"

[dependencies]
pest = "^2.1.0"
pest_derive = "^2.1.0"
lazy_static = "^1.4.0"
colored = "^2"